"""first migration

Revision ID: 79556fbbac1c
Revises:
Create Date: 2021-09-14 19:32:56.129616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '79556fbbac1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_normalized_name', table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.drop_column('projects', 'normalized_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('normalized_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index('ix_projects_normalized_name', 'projects', ['normalized_name'], unique=False)
    # ### end Alembic commands ###
