"""added normalized name project

Revision ID: c45f53551bf2
Revises: 3b2b83f5774a
Create Date: 2021-09-14 19:35:45.410804

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c45f53551bf2'
down_revision = '3b2b83f5774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('normalized_name', sa.String(), nullable=True))
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_normalized_name'), 'projects', ['normalized_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_normalized_name'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.drop_column('projects', 'normalized_name')
    # ### end Alembic commands ###
