"""added normalized name project

Revision ID: e5919c6dcc66
Revises: bcca1728b97c
Create Date: 2021-09-14 19:21:57.724224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5919c6dcc66'
down_revision = 'bcca1728b97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('normalized_name', sa.String(), nullable=False))
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_normalized_name'), 'projects', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_normalized_name'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.drop_column('projects', 'normalized_name')
    # ### end Alembic commands ###
