name: Deploy to Heroku
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy API to Heroku
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install -d
      - name: Check code linting
        working-directory: ${{ github.workspace }}
        run: |
          make lint
      - name: Run unit tests
        working-directory: ${{ github.workspace }}
        run: |
          make test
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
